# Generated by Django 5.0.7 on 2024-08-08 05:35

import uuid

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universities", "0002_alter_university_options_university_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Județ",
                "verbose_name_plural": "Județe",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=524)),
                ("url", models.CharField(max_length=128)),
                ("reviews_number", models.IntegerField(default=0)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculties_set",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facultate",
                "verbose_name_plural": "Facultăți",
            },
        ),
    ]
