# Generated by Django 5.0.7 on 2024-08-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="county",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="faculties_set",
                to="faculties.county",
            ),
            preserve_default=False,
        ),
    ]
