# Generated by Django 5.0.7 on 2024-10-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0003_alter_faculty_name_alter_faculty_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="description",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="url",
        ),
    ]
