# Generated by Django 5.0.7 on 2024-11-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0004_remove_faculty_description_remove_faculty_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='rating',
        ),
    ]
