# Generated by Django 5.0.7 on 2024-08-15 07:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculties", "0002_faculty_county"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grad_promo", models.CharField(default="", max_length=9)),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[("ST", "Student"), ("GR", "Absolvent")],
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pro", models.CharField(max_length=5555)),
                ("against", models.CharField(max_length=5555)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUB", "Trimis"),
                            ("REV", "În așteptare"),
                            ("ACC", "Acceptat"),
                            ("REJ", "Respins"),
                        ],
                        default="SUB",
                        max_length=3,
                    ),
                ),
                ("advice", models.CharField(max_length=1000)),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_set",
                        to="faculties.faculty",
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="favorite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Părere",
                "verbose_name_plural": "Păreri",
                "ordering": ["-publish"],
                "indexes": [
                    models.Index(
                        fields=["-publish"], name="reviews_rev_publish_af1cae_idx"
                    )
                ],
            },
        ),
    ]
