# Generated by Django 5.0.7 on 2024-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
