# Generated by Django 5.0.7 on 2024-09-18 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_review_favorites_alter_review_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="advice",
            field=models.CharField(
                max_length=1000,
                validators=[django.core.validators.MinLengthValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="against",
            field=models.CharField(
                max_length=5555,
                validators=[django.core.validators.MinLengthValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="pro",
            field=models.CharField(
                max_length=5555,
                validators=[django.core.validators.MinLengthValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Absolvent / Student"),
                    ("GR", "Absolvent"),
                    ("ST", "Student"),
                ],
                max_length=2,
            ),
        ),
    ]
