# Generated by Django 5.0.7 on 2024-11-27 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0005_remove_faculty_rating'),
        ('reviews', '0006_alter_review_advice_alter_review_against_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_type',
            field=models.CharField(choices=[('', 'Absolvent / Student'), ('GR', 'Absolvent'), ('ST', 'Student')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'faculty')},
        ),
    ]
