# Generated by Django 5.0.7 on 2024-11-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=None, max_length=150, null=True, unique=True),
        ),
    ]
