# Generated by Django 5.0.7 on 2024-08-07 14:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=524)),
                ("url", models.CharField(max_length=128)),
            ],
        ),
    ]
