# Generated by Django 5.0.7 on 2024-08-08 04:37

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={
                "verbose_name": "Universitate",
                "verbose_name_plural": "Universități",
            },
        ),
        migrations.AddField(
            model_name="university",
            name="name",
            field=models.CharField(default="Universitate", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="university",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="abc-def-ghi", editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
    ]
