# Generated by Django 5.0.7 on 2024-09-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0002_faculty_county"),
        ("universities", "0003_university_county"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="university",
            name="description",
        ),
        migrations.AddField(
            model_name="university",
            name="founded",
            field=models.CharField(default=1920, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="university",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="faculties.county",
            ),
        ),
    ]
