# Generated by Django 5.0.7 on 2024-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "universities",
            "0004_remove_university_description_university_founded_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="total_reviews",
            field=models.IntegerField(default=0),
        ),
    ]
