# Generated by Django 5.0.7 on 2024-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0005_university_total_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
